[package]

name = "RedStart"
version = "0.0.1"
authors = ["Dean4Devil <dean4devil@chaingamers.com>"]

[dependencies]
queryst = "0.1.1"
toml = "~0.1.3"

[dependencies.hyper]
path = "lib/hyper"

[dependencies.iron]
path = "lib/iron"
